variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

  SONAR_CLI_OPTS: >-
    -Dsonar.projectKey=gitlab-classrooms_gitlab-classrooms
    -Dsonar.organization=gitlab-classrooms
    -Dsonar.host.url=https://sonarcloud.io

image: maven:3-eclipse-temurin-17

cache:
  paths:
    - .m2/repository

verify:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar $SONAR_CLI_OPTS'

deploy:
  image:
    name: clevercloud/clever-tools
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
  script:
    - clever deploy
  environment:
    name: production
    deployment_tier: production
    url: https://gitlab-classrooms.cleverapps.io/
    action: start

pages:
  image:
    name: squidfunk/mkdocs-material
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
  script:
    - mkdocs build
  artifacts:
    paths:
      - site
