site_name: Gitlab Classrooms Docs

docs_dir: src/main/docs

repo_url: https://gitlab.univ-lille.fr/julien.wittouck/gitlab-classrooms

theme:
  name: material
  logo: logo.png
  icon:
    repo: fontawesome/brands/gitlab
